cutcalc_btns



        self.lbGrade1 = QLabel(self.centralwidget)
        self.lbGrade1.setObjectName(u"lbGrade1")
        sizePolicy_IP.setHeightForWidth(self.lbGrade1.sizePolicy().hasHeightForWidth())
        self.lbGrade1.setSizePolicy(sizePolicy_IP)
        self.lbGrade1.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbGrade1, 2, 0, 1, 1)

        self.lbRatio1 = QLabel(self.centralwidget)
        self.lbRatio1.setObjectName(u"lbRatio1")
        sizePolicy_IP.setHeightForWidth(self.lbRatio1.sizePolicy().hasHeightForWidth())
        self.lbRatio1.setSizePolicy(sizePolicy_IP)
        self.lbRatio1.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbRatio1, 2, 1, 1, 1)

        self.lbCut1 = QLabel(self.centralwidget)
        self.lbCut1.setObjectName(u"lbCut1")
        sizePolicy_IP.setHeightForWidth(self.lbCut1.sizePolicy().hasHeightForWidth())
        self.lbCut1.setSizePolicy(sizePolicy_IP)
        self.lbCut1.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbCut1, 2, 2, 1, 1)

        self.lbGrade2 = QLabel(self.centralwidget)
        self.lbGrade2.setObjectName(u"lbGrade2")
        sizePolicy_IP.setHeightForWidth(self.lbGrade2.sizePolicy().hasHeightForWidth())
        self.lbGrade2.setSizePolicy(sizePolicy_IP)
        self.lbGrade2.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbGrade2, 3, 0, 1, 1)

        self.lbRatio2 = QLabel(self.centralwidget)
        self.lbRatio2.setObjectName(u"lbRatio2")
        sizePolicy_IP.setHeightForWidth(self.lbRatio2.sizePolicy().hasHeightForWidth())
        self.lbRatio2.setSizePolicy(sizePolicy_IP)
        self.lbRatio2.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbRatio2, 3, 1, 1, 1)

        self.lbCut2 = QLabel(self.centralwidget)
        self.lbCut2.setObjectName(u"lbCut2")
        sizePolicy_IP.setHeightForWidth(self.lbCut2.sizePolicy().hasHeightForWidth())
        self.lbCut2.setSizePolicy(sizePolicy_IP)
        self.lbCut2.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbCut2, 3, 2, 1, 1)

        self.lbGrade3 = QLabel(self.centralwidget)
        self.lbGrade3.setObjectName(u"lbGrade3")
        sizePolicy_IP.setHeightForWidth(self.lbGrade3.sizePolicy().hasHeightForWidth())
        self.lbGrade3.setSizePolicy(sizePolicy_IP)
        self.lbGrade3.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbGrade3, 4, 0, 1, 1)

        self.lbRatio3 = QLabel(self.centralwidget)
        self.lbRatio3.setObjectName(u"lbRatio3")
        sizePolicy_IP.setHeightForWidth(self.lbRatio3.sizePolicy().hasHeightForWidth())
        self.lbRatio3.setSizePolicy(sizePolicy_IP)
        self.lbRatio3.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbRatio3, 4, 1, 1, 1)

        self.lbCut3 = QLabel(self.centralwidget)
        self.lbCut3.setObjectName(u"lbCut3")
        sizePolicy_IP.setHeightForWidth(self.lbCut3.sizePolicy().hasHeightForWidth())
        self.lbCut3.setSizePolicy(sizePolicy_IP)
        self.lbCut3.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbCut3, 4, 2, 1, 1)

        self.lbGrade4 = QLabel(self.centralwidget)
        self.lbGrade4.setObjectName(u"lbGrade4")
        sizePolicy_IP.setHeightForWidth(self.lbGrade4.sizePolicy().hasHeightForWidth())
        self.lbGrade4.setSizePolicy(sizePolicy_IP)
        self.lbGrade4.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbGrade4, 5, 0, 1, 1)

        self.lbRatio4 = QLabel(self.centralwidget)
        self.lbRatio4.setObjectName(u"lbRatio4")
        sizePolicy_IP.setHeightForWidth(self.lbRatio4.sizePolicy().hasHeightForWidth())
        self.lbRatio4.setSizePolicy(sizePolicy_IP)
        self.lbRatio4.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbRatio4, 5, 1, 1, 1)

        self.lbCut4 = QLabel(self.centralwidget)
        self.lbCut4.setObjectName(u"lbCut4")
        sizePolicy_IP.setHeightForWidth(self.lbCut4.sizePolicy().hasHeightForWidth())
        self.lbCut4.setSizePolicy(sizePolicy_IP)
        self.lbCut4.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbCut4, 5, 2, 1, 1)

        self.lbGrade5 = QLabel(self.centralwidget)
        self.lbGrade5.setObjectName(u"lbGrade5")
        sizePolicy_IP.setHeightForWidth(self.lbGrade5.sizePolicy().hasHeightForWidth())
        self.lbGrade5.setSizePolicy(sizePolicy_IP)
        self.lbGrade5.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbGrade5, 6, 0, 1, 1)

        self.lbRatio5 = QLabel(self.centralwidget)
        self.lbRatio5.setObjectName(u"lbRatio5")
        sizePolicy_IP.setHeightForWidth(self.lbRatio5.sizePolicy().hasHeightForWidth())
        self.lbRatio5.setSizePolicy(sizePolicy_IP)
        self.lbRatio5.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbRatio5, 6, 1, 1, 1)

        self.lbCut5 = QLabel(self.centralwidget)
        self.lbCut5.setObjectName(u"lbCut5")
        sizePolicy_IP.setHeightForWidth(self.lbCut5.sizePolicy().hasHeightForWidth())
        self.lbCut5.setSizePolicy(sizePolicy_IP)
        self.lbCut5.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbCut5, 6, 2, 1, 1)

        self.lbGrade6 = QLabel(self.centralwidget)
        self.lbGrade6.setObjectName(u"lbGrade6")
        sizePolicy_IP.setHeightForWidth(self.lbGrade6.sizePolicy().hasHeightForWidth())
        self.lbGrade6.setSizePolicy(sizePolicy_IP)
        self.lbGrade6.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbGrade6, 7, 0, 1, 1)

        self.lbRatio6 = QLabel(self.centralwidget)
        self.lbRatio6.setObjectName(u"lbRatio6")
        sizePolicy_IP.setHeightForWidth(self.lbRatio6.sizePolicy().hasHeightForWidth())
        self.lbRatio6.setSizePolicy(sizePolicy_IP)
        self.lbRatio6.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbRatio6, 7, 1, 1, 1)

        self.lbCut6 = QLabel(self.centralwidget)
        self.lbCut6.setObjectName(u"lbCut")
        sizePolicy_IP.setHeightForWidth(self.lbCut.sizePolicy().hasHeightForWidth())
        self.lbCut6.setSizePolicy(sizePolicy_IP)
        self.lbCut6.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbCut, 7, 2, 1, 1)

        self.lbGrade7 = QLabel(self.centralwidget)
        self.lbGrade7.setObjectName(u"lbGrade7")
        sizePolicy_IP.setHeightForWidth(self.lbGrade7.sizePolicy().hasHeightForWidth())
        self.lbGrade7.setSizePolicy(sizePolicy_IP)
        self.lbGrade7.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbGrade7, 8, 0, 1, 1)

        self.lbRatio7 = QLabel(self.centralwidget)
        self.lbRatio7.setObjectName(u"lbRatio7")
        sizePolicy_IP.setHeightForWidth(self.lbRatio7.sizePolicy().hasHeightForWidth())
        self.lbRatio7.setSizePolicy(sizePolicy_IP)
        self.lbRatio7.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbRatio7, 8, 1, 1, 1)

        self.lbCut7 = QLabel(self.centralwidget)
        self.lbCut7.setObjectName(u"lbCut7")
        sizePolicy_IP.setHeightForWidth(self.lbCut7.sizePolicy().hasHeightForWidth())
        self.lbCut7.setSizePolicy(sizePolicy_IP)
        self.lbCut7.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbCut7, 8, 2, 1, 1)

        self.lbGrade8 = QLabel(self.centralwidget)
        self.lbGrade8.setObjectName(u"lbGrade8")
        sizePolicy_IP.setHeightForWidth(self.lbGrade8.sizePolicy().hasHeightForWidth())
        self.lbGrade8.setSizePolicy(sizePolicy_IP)
        self.lbGrade8.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbGrade8, 9, 0, 1, 1)

        self.lbRatio8 = QLabel(self.centralwidget)
        self.lbRatio8.setObjectName(u"lbRatio8")
        sizePolicy_IP.setHeightForWidth(self.lbRatio8.sizePolicy().hasHeightForWidth())
        self.lbRatio8.setSizePolicy(sizePolicy_IP)
        self.lbRatio8.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbRatio8, 9, 1, 1, 1)

        self.lbCut8 = QLabel(self.centralwidget)
        self.lbCut8.setObjectName(u"lbCut8")
        sizePolicy_IP.setHeightForWidth(self.lbCut8.sizePolicy().hasHeightForWidth())
        self.lbCut8.setSizePolicy(sizePolicy_IP)
        self.lbCut8.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbCut8, 9, 2, 1, 1)

        self.lbGrade9 = QLabel(self.centralwidget)
        self.lbGrade9.setObjectName(u"lbGrade9")
        sizePolicy_IP.setHeightForWidth(self.lbGrade9.sizePolicy().hasHeightForWidth())
        self.lbGrade9.setSizePolicy(sizePolicy_IP)
        self.lbGrade9.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbGrade9, 10, 0, 1, 1)

        self.lbRatio9 = QLabel(self.centralwidget)
        self.lbRatio9.setObjectName(u"lbRatio9")
        sizePolicy_FP.setHeightForWidth(self.lbRatio9.sizePolicy().hasHeightForWidth())
        self.lbRatio9.setSizePolicy(sizePolicy_FP)
        self.lbRatio9.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbRatio9, 10, 1, 1, 1)

        self.lbCut9 = QLabel(self.centralwidget)
        self.lbCut9.setObjectName(u"lbCut9")
        sizePolicy_IP.setHeightForWidth(self.lbCut9.sizePolicy().hasHeightForWidth())
        self.lbCut9.setSizePolicy(sizePolicy_IP)
        self.lbCut9.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.lbCut9, 10, 2, 1, 1)

cutcalc_btns_retranslate
        
        self.lbGrade1.setText(QCoreApplication.translate("CutCalc", u"1", None))
        self.lbRatio1.setText("")
        self.lbGrade2.setText(QCoreApplication.translate("CutCalc", u"2", None))
        self.lbGrade3.setText(QCoreApplication.translate("CutCalc", u"3", None))
        self.lbGrade4.setText(QCoreApplication.translate("CutCalc", u"4", None))
        self.lbGrade5.setText(QCoreApplication.translate("CutCalc", u"5", None))
        self.lbGrade6.setText(QCoreApplication.translate("CutCalc", u"6", None))
        self.lbGrade7.setText(QCoreApplication.translate("CutCalc", u"7", None))
        self.lbGrade8.setText(QCoreApplication.translate("CutCalc", u"8", None))
        self.lbGrade9.setText(QCoreApplication.translate("CutCalc", u"9", None))
        self.lbRatio9.setText(QCoreApplication.translate("CutCalc", u"100%", None))

